In [1]:
import numpy as np

In [2]:
import sympy as sp

In [3]:
def LU(A, L, U, n):
    #print("A: \n",A)
    if (U[0][0] != 0):
        for i in range(0, n):
            L[i][0] = A[i][0]/U[0][0]
            U[0][i] = A[0][i]/L[0][0]
    else:
        for i in range(0, n):
            U[0][i] = A[0][i]/L[0][0]
            L[i][0] = A[i][0]/U[0][0]
    for k in range(0, n):
        if (U[k][k]!=0):
            for i in range(k, n):
                sum = 0
                for m in range(0, k):
                    sum += L[i][m]*U[m][k]
                L[i][k] = (1 / U[k][k]) * (A[i][k] - sum)
            for j in range (k, n):
                sum = 0
                for m in range (0, k):
                    sum += L[k][m] * U[m][j]
                U[k][j] = (1 / L[k][k]) * (A[k][j] - sum)
        else:
            for j in range (k, n):
                sum = 0
                for m in range (0, k):
                    sum += L[k][m] * U[m][j]
                U[k][j] = (1 / L[k][k]) * (A[k][j] - sum)
            for i in range(k, n):
                sum = 0
                for m in range(0, k):
                    sum += L[i][m]*U[m][k]
                L[i][k] = (1 / U[k][k]) * (A[i][k] - sum)
    print("L: \n",np.round_(L, 2))
    print("U: \n",np.round_(U, 2))
    return np.round_(L, 2), np.round_(U, 2)


In [4]:
def check_LU_result(A, L, U):
    res = np.matmul(L, U)
    return np.allclose(res, A)

In [18]:
a_matrix = np.array([[5, 7, 6, 5], [7, 10, 8, 7], [6, 8, 10, 9], [5, 7, 9, 10]], dtype=float)
#L = np.zeros((4, 4), dtype=float)
#U = np.zeros((4, 4), dtype=float)
#LU_l(a_matrix, U, 1., 1., 4)
L = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]], dtype=float)
U = np.zeros((4, 4))
LU(a_matrix, L, U, np.size(L[0]))
print(check_LU_result(a_matrix, L, U))
L = np.zeros((4, 4))
U = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]], dtype=float)
LU(a_matrix, L, U, np.size(L[0]))
print(check_LU_result(a_matrix, L, U))
L = np.array([[1, 0, 0, 0], [0, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 0]], dtype=float)
U = np.array([[0, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]], dtype=float)
LU(a_matrix, L, U, np.size(L[0]))
print(check_LU_result(a_matrix, L, U))
L = np.array([[0, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]], dtype=float)
U = np.array([[1, 0, 0, 0], [0, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 0]], dtype=float)
LU(a_matrix, L, U, np.size(L[0]))
print(check_LU_result(a_matrix, L, U))
L = np.array([[0, 0, 0, 0], [0, 0,0, 0], [0, 0, 7,0], [0, 0, 0, 9]], dtype=float)
U = np.array([[3, 0, 0, 0], [0, 5, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], dtype=float)
LU(a_matrix, L, U, np.size(L[0]))
print(check_LU_result(a_matrix, L, U))

L: 
 [[ 1.   0.   0.   0. ]
 [ 1.4  1.   0.   0. ]
 [ 1.2 -2.   1.   0. ]
 [ 1.   0.   1.5  1. ]]
U: 
 [[ 5.   7.   6.   5. ]
 [ 0.   0.2 -0.4 -0. ]
 [ 0.   0.   2.   3. ]
 [ 0.   0.   0.   0.5]]
True
L: 
 [[ 5.   0.   0.   0. ]
 [ 7.   0.2  0.   0. ]
 [ 6.  -0.4  2.   0. ]
 [ 5.  -0.   3.   0.5]]
U: 
 [[ 1.   1.4  1.2  1. ]
 [ 0.   1.  -2.   0. ]
 [ 0.   0.   1.   1.5]
 [ 0.   0.   0.   1. ]]
True
L: 
 [[ 1.   0.   0.   0. ]
 [ 1.4  0.2  0.   0. ]
 [ 1.2 -0.4  1.   0. ]
 [ 1.   0.   1.5  0.5]]
U: 
 [[ 5.  7.  6.  5.]
 [ 0.  1. -2. -0.]
 [ 0.  0.  2.  3.]
 [ 0.  0.  0.  1.]]
True
L: 
 [[ 5.  0.  0.  0.]
 [ 7.  1.  0.  0.]
 [ 6. -2.  2.  0.]
 [ 5. -0.  3.  1.]]
U: 
 [[ 1.   1.4  1.2  1. ]
 [ 0.   0.2 -0.4  0. ]
 [ 0.   0.   1.   1.5]
 [ 0.   0.   0.   0.5]]
True
L: 
 [[ 1.67  0.    0.    0.  ]
 [ 2.33  0.04  0.    0.  ]
 [ 2.   -0.08  7.    0.  ]
 [ 1.67 -0.   10.5   9.  ]]
U: 
 [[  3.     4.2    3.6    3.  ]
 [  0.     5.   -10.     0.  ]
 [  0.     0.     0.29   0.43]
 [  0.     0.   

In [39]:
def multi_newton(Li, Ui, Df, f, k):
    X = np.array([[1, 1]], dtype=float).reshape(2,1)
    h = 0.
    L = np.zeros((2,2), dtype=float)
    U = np.zeros((2,2), dtype=float)
    for i in range(k):
        L, U = LU(Df(X[0],X[1]), Li, Ui, np.size(L[0]))
        y = forward_solve(L, -f(X[0],X[1]))
        h = back_solve(U, y)
        X += h.reshape(2,1)
    return X[0], X[1]

In [8]:
def forward_solve(A, b):
    n = len(b)
    x = np.zeros(n)
    for i in range(n):
        x[i] = b[i]
        for j in range(0,i):
            x[i] -= A[i][j] * x[j]
        x[i] /= A[i][i]
    return x

In [9]:
def back_solve(A, b):
    n = len(b)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = b[i]
        for j in range(0,i):
            x[i] -= A[i][j] * x[j]
        x[i] /= A[i][i]
    return x

In [48]:
x, y = sp.symbols("x, y")
f_mat = sp.Matrix([x**2 + y**2 - 5, x + 2*y - 4])
D = f_mat.jacobian(sp.Matrix([x, y]))
s = (x, y)
d_func = sp.lambdify(s, D, modules='numpy')
f_func = sp.lambdify(s, f_mat, modules='numpy')
Li = np.array([[1, 0], [0, 1]], dtype=float)
Ui = np.array([[0, 0], [0, 0]], dtype=float)
it = 5
X = multi_newton(Li, Ui, d_func, f_func, it)
print("\nx(",it,") =", X[0],",",X[1],"\n")

[[1.]
 [1.]]
L: 
 [[1.  0. ]
 [0.5 1. ]]
U: 
 [[2. 2.]
 [0. 1.]]
L: 
 [[2.5 0. ]
 [0.5 1.8]]
U: 
 [[2.  0.4]
 [0.  1. ]]
L: 
 [[2.2  0.  ]
 [0.5  1.57]]
U: 
 [[2.   0.86]
 [0.   1.  ]]
L: 
 [[2.03 0.  ]
 [0.5  1.51]]
U: 
 [[2.   0.98]
 [0.   1.  ]]
L: 
 [[2.  0. ]
 [0.5 1.5]]
U: 
 [[2. 1.]
 [0. 1.]]

x( 5 ) = [2.00007187] , [1.00000178] 

